apiVersion: v2
description: A Helm chart for installing cert-manager-webhook-loopia in Kubernetes
name: cert-manager-webhook-loopia
version: 1.2
maintainers:
  - name: tekn0ir
    url: https://github.com/tekn0ir/cert-manager-webhook-loopia